sonar.projectKey=rayondemiel-chantepafo
sonar.organization=rayondemiel

sonar.sources=backend/app,frontend/src
sonar.tests=backend/tests,frontend/tests

sonar.exclusions=**/node_modules/**,**/.venv/**,**/dist/**,**/__pycache__/**,**/*.d.ts
sonar.test.inclusions=**/*.test.ts,backend/tests/**/*.py

sonar.python.version=3.12
sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info

sonar.sourceEncoding=UTF-8
